const misCamisetas = [
    {id: "1", nombre: "Camiseta de Arsenal", precio: 18000, img: '../img/Adidas/Arsenal.jpg', idMarca: "adidas", descripcion: "La camiseta de fútbol del Arsenal está confeccionada con materiales de alta calidad, utilizando el tejido adidas AEROREADY que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta el clásico color rojo con detalles en blanco, y destaca por los toques dorados que celebran la rica historia del club. El escudo del Arsenal y el logo de adidas están bordados, asegurando durabilidad y un acabado premium."},
    {id: "2", nombre: "Camiseta de España", precio: 22000, img: '../img/Adidas/España.jpg', idMarca: "adidas", descripcion: "La camiseta de fútbol de la selección española está confeccionada con materiales de alta calidad, utilizando el tejido adidas AEROREADY que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta el clásico color rojo con detalles en amarillo, simbolizando la pasión y el orgullo nacional. El escudo de la Real Federación Española de Fútbol y el logo de adidas están bordados, asegurando durabilidad y un acabado premium."},
    {id: "3", nombre: "Camiseta de Real Madrid", precio: 26500, img: '../img/Adidas/RealMadrid.jpg', idMarca: "adidas", descripcion: "La camiseta de fútbol del Real Madrid está confeccionada con materiales de alta calidad, utilizando el tejido adidas AEROREADY que proporciona una excelente transpirabilidad y comodidad. Su diseño es puro y minimalista, destacando el icónico color blanco que representa la grandeza del club. Los detalles en dorado añaden un toque de elegancia, mientras que el escudo del club y el logo de adidas están bordados, asegurando durabilidad y un acabado premium."},
    {id: "4", nombre: "Camiseta de Barcelona", precio: 26000, img: '../img/Nike/Barcelona.jpg', idMarca: "nike", descripcion: "La camiseta de fútbol del FC Barcelona está confeccionada con materiales de alta calidad, utilizando el tejido Nike Dri-FIT ADV que proporciona una excelente transpirabilidad y comodidad durante el juego. Su diseño presenta los tradicionales colores blaugranas, con franjas verticales en azul y granate, y detalles en dorado que aportan un toque de elegancia. Además, el escudo del club y el logo de Adidas están bordados, lo que añade durabilidad y un acabado premium"},
    {id: "5", nombre: "Camiseta de Portugal", precio: 21000, img: '../img/Nike/Portugal.jpg', idMarca: "nike", descripcion: "La camiseta de fútbol de la selección de Portugal está confeccionada con materiales de alta calidad, utilizando el tejido Nike Dri-FIT ADV que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta los colores tradicionales de Portugal, con el rojo y verde predominantes, y detalles en dorado que añaden un toque de elegancia. El escudo de la Federación Portuguesa de Fútbol y el logo de Nike están bordados, asegurando durabilidad y un acabado premium."},
    {id: "6", nombre: "Camiseta de PSG", precio: 16000, img: '../img/Nike/PSG.jpg', idMarca: "nike", descripcion: "La camiseta de fútbol del Paris Saint-Germain está confeccionada con materiales de alta calidad, utilizando el tejido Nike Dri-FIT ADV que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta el icónico color azul marino con detalles en rojo y blanco, reflejando la identidad del club. El escudo del PSG y el logo de Nike están bordados, asegurando durabilidad y un acabado premium."},
    {id: "7", nombre: "Camiseta de Independiente", precio: 15350, img: '../img/Puma/Independiente.jpg', idMarca: "puma", descripcion: "La camiseta de fútbol del Club Atlético Independiente está confeccionada con materiales de alta calidad, utilizando el tejido Puma dryCELL que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta el icónico color rojo con detalles en blanco, reflejando la rica historia del club. El escudo de Independiente y el logo de Puma están bordados, asegurando durabilidad y un acabado premium."},
    {id: "8", nombre: "Camiseta de Manchester City", precio: 25000, img: '../img/Puma/ManchesterCity.jpg', idMarca: "puma", descripcion: "La camiseta de fútbol del Manchester City está confeccionada con materiales de alta calidad, utilizando el tejido Puma dryCELL que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta el icónico color celeste con detalles en blanco y azul marino, reflejando la identidad del club. El escudo del Manchester City y el logo de Puma están bordados, asegurando durabilidad y un acabado premium."},
    {id: "9", nombre: "Camiseta de Rosario Central", precio: 13500, img: '../img/Puma/RosarioCentral.jpg', idMarca: "puma", descripcion: "La camiseta de fútbol de Rosario Central está confeccionada con materiales de alta calidad, utilizando el tejido Umbro que proporciona una excelente transpirabilidad y comodidad. Su diseño presenta los tradicionales colores azul y amarillo, con franjas verticales que reflejan la identidad del club. El escudo de Rosario Central y el logo de Umbro están bordados, asegurando durabilidad y un acabado premium."},
    {id: "10", nombre: "Camiseta de Colo Colo", precio: 14000, img: '../img/UnderArmour/ColoColo.jpg', idMarca: "under armour", descripcion: "La camiseta de fútbol del Colo Colo, fabricada por Under Armour, destaca por su diseño elegante y funcional. Predominantemente blanca, cuenta con detalles en negro, como el logo del club y los acentos en las mangas y el cuello. Está confeccionada con materiales de alta calidad que garantizan durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El tejido es ligero y transpirable, permitiendo una excelente movilidad en el campo. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda imprescindible para los fanáticos del 'Cacique'."},
    {id: "11", nombre: "Camiseta de Estudiantes", precio: 14500, img: '../img/UnderArmour/Estudiantes.jpg', idMarca: "under armour", descripcion: "La camiseta de fútbol de Estudiantes de La Plata, diseñada por la marca Under Armour, es una pieza que combina tradición e innovación. Predominantemente roja, presenta detalles en blanco, incluyendo el logo del club y los vivos en las mangas y el cuello. La camiseta está confeccionada con materiales de alta calidad que aseguran durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El diseño incluye recortes audaces y un ajuste entallado que resalta la figura del jugador, inspirado en un concepto futurista y de superhéroes. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda destacada para los fanáticos del 'Pincha'."},
    {id: "12", nombre: "Camiseta de San Paulo", precio: 15000, img: '../img/UnderArmour/SaoPaulo.jpg', idMarca: "under armour", descripcion: "La camiseta de fútbol del São Paulo FC, diseñada por Under Armour, es una muestra de elegancia y tradición. Predominantemente blanca, presenta dos finas rayas horizontales en el pecho, una roja y otra negra, que representan los colores icónicos del club. El logo del São Paulo se sitúa en el centro de estas rayas, destacando con orgullo. La camiseta está confeccionada con materiales de alta calidad que aseguran durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El diseño incluye detalles en el cuello y las mangas, que añaden un toque de sofisticación. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda esencial para los fanáticos del 'Tricolor Paulista'"},
    {id: "13", nombre: "Camiseta de Huracan", precio: 14350, img: '../img/Kappa/Huracan.jpg', idMarca: "kappa", descripcion: "La camiseta de fútbol del Club Atlético Huracán, diseñada por Kappa, es una pieza que combina tradición y modernidad. Predominantemente blanca, presenta detalles en rojo en el cuello, los bordes de las mangas y los laterales. El logo del club se sitúa en el pecho, destacando con orgullo. La camiseta está confeccionada con materiales de alta calidad que aseguran durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El diseño incluye un ajuste entallado que permite una excelente movilidad en el campo. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda esencial para los fanáticos del 'Globo'"},
    {id: "14", nombre: "Camiseta de Racing", precio: 14600, img: '../img/Kappa/Racing.jpg', idMarca: "kappa", descripcion: "La camiseta de fútbol del Racing Club, diseñada por Kappa, es una pieza que refleja la rica historia y el espíritu combativo del club. Predominantemente blanca, cuenta con detalles en celeste en el cuello y los bordes de las mangas, así como el escudo del club en el pecho. La camiseta está confeccionada con materiales de alta calidad que aseguran durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El diseño incluye un ajuste entallado que permite una excelente movilidad en el campo. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda esencial para los fanáticos de 'La Academia'"},
    {id: "15", nombre: "Camiseta de Tigre", precio: 12500, img: '../img/Kappa/Tigre.jpg', idMarca: "kappa", descripcion: " La camiseta de fútbol del Club Atlético Tigre, diseñada por Kappa, es predominantemente blanca, con detalles en azul y rojo que le dan un toque distintivo. El escudo del club se sitúa en el pecho, destacando con orgullo. La camiseta está confeccionada con materiales de alta calidad que aseguran durabilidad y comodidad, utilizando tecnología de absorción de humedad para mantener a los jugadores frescos y secos durante el juego. El diseño incluye un ajuste entallado que permite una excelente movilidad en el campo. La atención al detalle y la calidad de los acabados hacen de esta camiseta una prenda esencial para los fanáticos del 'Matador'."}
]

export const getCamisetas = () => {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(misCamisetas)
        }, 100);
    })
}

export const getUnaCamiseta = (id) => {
    return new Promise(resolve => {
        setTimeout(() => {
            const camiseta = misCamisetas.find(item => item.id === id)
            resolve(camiseta)
        }, 100);
    })
}

export const getMarca = (idMarca) => {
    return new Promise(resolve => {
        setTimeout(() => {
            const camiseta = misCamisetas.filter(item => item.idMarca === idMarca)
            resolve(camiseta)
        }, 100);
    })
}